### ISSUE TITLE
Doesn't seem to work without refreshing page

### ISSUE THREAD

**Issue by XhmikosR** [notwaldorf/github-canned-responses#14]
Hello, there.

So, I'm trying this with Firefox 45-beta5 x64 on Windows 10.

---

Initial page load

![2016-02-13_17-43-23](https://cloud.githubusercontent.com/assets/349621/13028502/975eee24-d279-11e5-838e-69479c7404d1.png)

After page refresh

![2016-02-13_17-43-41](https://cloud.githubusercontent.com/assets/349621/13028508/abf4ad42-d279-11e5-96bf-e988d64a6a70.png)

**Comment by janriemer** [comment]
It is the same with Firefox 44.0.2 on Windows 8.1.

**Comment by notwaldorf** [comment]
Oof, I've tried it on 44.0.2 on a Mac, but unfortunately I don't have a Windows machine to test this on :(

**Comment by janriemer** [comment]
Well, I've observed another interesting behaviour:
When I visit this issue **coming from github's notification menu**,
it is working, so **no page refresh** needed in that case.

That seems to be a tough one... :sweat:

**Comment by notwaldorf** [comment]
You're right: on FF (and not Chrome), if I go to https://github.com/notwaldorf/github-canned-responses/issues for example and then click on an issue, there's no button. If i click back and then forward, it appears (sigh)

There used to be a problem sometimes with the back/forward menu, because in some cases GitHub doesn't do a page refresh (steps: 1. go to meowni.ca. 2. go to an open issue directly. 3. click back. 4. click forward. 5. button used to be gone). I've fixed that with a gigantor history state hack -- I'm suspicious a similar one is needer, or (worse), that one is interfering with this flow.

I'll try to debug this soon but if anyone gets a chance to do it first, internet points for you! 🏆

**Comment by DraperStudio** [comment]
I am having pretty much this exact issue with both the latest Chrome Stable and Chrome Canary except that refreshing the page doesn't help at all.

**Comment by notwaldorf** [comment]
Unfortunately, this element is no longer maintained since GitHub shipped this as a built-in feature
