### ISSUE TITLE
FFx extension: content is reset to default

### ISSUE THREAD

**Issue by xBorderie** [notwaldorf/github-canned-responses#20]
Hey there!
This extensions is extremely helpful, thank you!
Sadly, it seems that it keeps deleting the responses I add, leaving me with only the default ones -- and having to dive into past PR answers in order to retrieve the responses and re-add them.
It seems to happen when I close/reopen Firefox. I'll do more tests to see if the content is actually reset to default (meaning that the default responses that I deleted are back every time), and report here.
Thank you!

**Comment by shockwavemoto** [comment]
Hey there!
This extensions is extremely helpful, thank you!
Sadly, it seems that it keeps deleting the responses I add, leaving me with only the default ones -- and having to dive into past PR answers in order to retrieve the responses and re-add them.
It seems to happen when I close/reopen Firefox. I'll do more tests to see if the content is actually reset to default (meaning that the default responses that I deleted are back every time), and report here.
Thank you!

**Comment by xBorderie** [comment]
Indeed. My wild guess is that shockwavemoto is a spam account. I can tell from the duplicated pixels.
